[package]
name = "storage-database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Storage database functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
