[package]
name = "validator-staking"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "validator staking functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
