[package]
name = "api-versioning"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "API versioning functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
