[package]
name = "cc-chain-consensus"
version = "1.0.0"
edition = "2021"
rust-version = "1.89.0"
description = "CC Chain Consensus - BFT consensus implementation with safety system"
license = "MIT"
repository = "https://github.com/ccx404/cc-chain"
keywords = ["blockchain", "consensus", "bft", "byzantine"]
categories = ["cryptography", "network-programming"]

[dependencies]
# Local workspace dependencies
cc-chain-sdk = { path = "../cc-chain-sdk" }

# External workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }
crossbeam = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }