[package]
name = "bridge-utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "bridge utilities functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
