[package]
name = "networking-gossip"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Networking gossip functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
