[package]
name = "metrics-aggregation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "metrics aggregation functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
