[package]
name = "examples-tutorials"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "examples tutorials functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
