[package]
name = "cc-core-consensus_helpers"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CC Chain core consensus_helpers functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
