[package]
name = "bridge-recovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "bridge recovery functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
