[package]
name = "cc-chain-storage"
version = "1.0.0"
edition = "2021"
rust-version = "1.89.0"
description = "CC Chain Storage - Memory pool and storage management"
license = "MIT"
repository = "https://github.com/ccx404/cc-chain"
keywords = ["blockchain", "storage", "mempool"]
categories = ["data-structures"]

[dependencies]
# Local workspace dependencies
cc-chain-sdk = { path = "../cc-chain-sdk" }

# External workspace dependencies
parking_lot = { workspace = true }
dashmap = { workspace = true }
lru = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }