[package]
name = "api-endpoints"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "API endpoints functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
