[package]
name = "api-validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "API validation functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
