[package]
name = "testing-stress"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "testing stress functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
