[package]
name = "sdk-transactions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "sdk transactions functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
