[package]
name = "gateway-caching"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "gateway caching functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
