[package]
name = "bridge-validators"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "bridge validators functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
