[package]
name = "api-monitoring"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "API monitoring functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
