[package]
name = "docs-architecture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "docs architecture functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
