[package]
name = "sdk-utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "sdk utilities functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
