[package]
name = "networking-protocols"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Networking protocols functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
