[package]
name = "monitor-diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "monitor diagnostics functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
