[package]
name = "explorer-visualization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "explorer visualization functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
