[package]
name = "explorer-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "explorer search functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
