[package]
name = "cli-errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "cli errors functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
