[package]
name = "networking-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Networking security functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
