[package]
name = "docs-guides"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "docs guides functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
