[package]
name = "wallet-interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "wallet interface functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
