[package]
name = "cc-core-state_management"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CC Chain core state_management functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
