[package]
name = "docs-specifications"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "docs specifications functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
