[package]
name = "gateway-documentation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "gateway documentation functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
