[package]
name = "tools-optimization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "tools optimization functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
