[package]
name = "cc-core-utilities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CC Chain core utilities functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
