[package]
name = "rpc-methods"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "rpc methods functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
