[package]
name = "consensus-recovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Consensus recovery functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
