[package]
name = "consensus-metrics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Consensus metrics functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
