[package]
name = "examples-basic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "examples basic functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
