[package]
name = "gateway-load_balancing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "gateway load_balancing functionality"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
